version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    working_directory: /home/builder/
    steps:
      - run:
          name: Demo
          command: |
            echo -e "\n Where am I?!\n"
            pwd
            ls -la .
            tree

            echo -e "\n rename test"
            which rename
            RenExec=$(which rename 2>/dev/null)
            if [[ -z $RenExec ]]; do echo "rename not found!"; apt-get -qqy update && apt-get -qqy install rename; which rename && rename --help; done; fi

            echo -e "\n lscpu test"
            lscpu && lscpu --extended --all

            echo -e "\n nproc test"
            nproc --all

            which make && make -V

workflows:
  version: 2
  tester:
    jobs:
      - build:
          context: personal-envs
