version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      TERM: xterm-256color
    working_directory: /home/builder/test/
    steps:
      - run:
          name: Demo
          command: |
            # Colors
            CL_XOS="\033[34;1m"; CL_PFX="\033[33m"; CL_INS="\033[36m"; CL_RED="\033[31m"; CL_GRN="\033[32m"; CL_YLW="\033[33m"; CL_BLU="\033[34m"; CL_MAG="\033[35m"; CL_CYN="\033[36m"; CL_RST="\033[0m"

            echo -e "$CL_XOS Where am I? $CL_RST"
            printf "$CL_BLU Using printf. So, where were we?! $CL_RST"
            pwd
            ls -la .
            tree

            echo -e "\n $TERM \n\n"
            echo -e "\n rename test"
            which rename
            RenExec=$(which rename 2>/dev/null)
            if [[ -z $RenExec ]]; then
              echo "rename not found!"
              apt-get -qqy update && apt-get -qqy install rename
              which rename && rename --help
            fi

            echo -e "\n lscpu test"
            lscpu && lscpu --extended --all

            echo -e "\n nproc test"
            nproc --all

            mkdir subs
            echo -e "Some Data\nThat need to be on\nA file" > subs/demo_data.txt
            ls -la *
            rename 's/\.txt$/_renamed.txt/' subs/*txt
            ls -la *

workflows:
  version: 2
  tester:
    jobs:
      - build:
          context: personal-envs
